import { Metadata } from "next";
import Link from "next/link";

const posts: Record<string, { title: string; date: string; content: string[] }> = {
  "proc-je-dobry-napad-pouzivat-ai": {
    title: "Proč je dobrý nápad používat AI",
    date: "2026-07-24",
    content: [
      "",
      "**Hlavní myšlenka**",
      "",
      "Umělá inteligence představuje největší zvýšení osobní produktivity od nástupu internetu. Její hodnota nespočívá v tom, že by nahrazovala člověka, ale v tom, že člověku umožňuje dosáhnout lepších výsledků za kratší dobu. AI nám vrací čas, pomáhá dělat lepší rozhodnutí a odbourává činnosti, které nepřinášejí skutečnou hodnotu.",
      "",
      "Zatímco dříve bylo nutné desítky minut hledat informace, zpracovávat dokumenty nebo vytvářet reporty, dnes může většinu přípravných prací zvládnout AI během několika sekund.",
      "",
      "---",
      "",
      "**Co AI umí automatizovat**",
      "",
      "Každý člověk tráví významnou část dne opakujícími se úkoly. Jedná se o činnosti, které nevyžadují kreativitu ani hlubší přemýšlení, přesto spotřebovávají velké množství času.",
      "",
      "Typické příklady:",
      "třídění a zpracování e-mailů,",
      "vytváření zápisů ze schůzek,",
      "vyplňování formulářů,",
      "vyhledávání informací,",
      "tvorba reportů,",
      "přepisování poznámek,",
      "plánování harmonogramů,",
      "příprava prezentací.",
      "",
      "**Příklad časové úspory**",
      "",
      "Pokud zaměstnanec stráví denně:",
      "30 minut e-maily,",
      "20 minut hledáním podkladů,",
      "20 minut tvorbou dokumentů,",
      "",
      "AI může značnou část této práce zkrátit na polovinu. To znamená úsporu přibližně 35 až 40 minut každý den.",
      "",
      "Za rok to představuje více než 150 hodin času.",
      "",
      "---",
      "",
      "**Jak AI akceleruje lidskou práci**",
      "",
      "Největší přínos AI není ve vykonávání práce za člověka, ale v její akceleraci.",
      "",
      "AI funguje podobně jako zkušený asistent, který:",
      "okamžitě připraví první návrh,",
      "navrhne strukturu řešení,",
      "shrne stovky stran textu,",
      "najde informace napříč zdroji,",
      "navrhne alternativní postupy.",
      "",
      "**Praktický příklad**",
      "",
      "Vytvoření prezentace často zabere 2 až 4 hodiny.",
      "S využitím AI lze:",
      "během několika minut vytvořit osnovu,",
      "připravit obsah jednotlivých slidů,",
      "navrhnout klíčové argumenty,",
      "připravit shrnutí pro vedení.",
      "",
      "Výsledný čas může klesnout na méně než polovinu.",
      "",
      "---",
      "",
      "**Jak zvyšuje kvalitu výsledků**",
      "",
      "AI není jen nástroj na šetření času.",
      "Dokáže fungovat jako permanentní kontrolor kvality.",
      "",
      "Pomáhá:",
      "odhalovat chyby,",
      "kontrolovat logiku argumentace,",
      "hledat rozpory v dokumentech,",
      "zlepšovat formulace,",
      "vytvářet srozumitelnější texty,",
      "generovat nové pohledy na problém.",
      "",
      "Tam, kde člověk pracuje pod tlakem nebo ve spěchu, funguje AI jako druhý pár očí.",
      "Výsledkem jsou kvalitnější výstupy, méně oprav a méně ztraceného času.",
      "",
      "---",
      "",
      "**Více prostoru pro kreativitu**",
      "",
      "Lidé vytvářejí největší hodnotu tehdy, když přemýšlejí, inovují a spolupracují.",
      "Právě zde AI vytváří největší přínos.",
      "",
      "Když převezme rutinní činnosti, vzniká prostor pro:",
      "strategické plánování,",
      "práci se zákazníky,",
      "rozvoj nových nápadů,",
      "vzdělávání,",
      "osobní rozvoj,",
      "budování vztahů.",
      "",
      "AI tedy neomezuje lidský potenciál. Naopak ho uvolňuje.",
      "",
      "---",
      "",
      "**Přínos v osobním životě**",
      "",
      "Většina lidí si AI spojuje s pracovním prostředím. Ve skutečnosti však může přinášet stejně významné výhody i doma.",
      "",
      "Příklady využití:",
      "plánování dovolené,",
      "sestavení itineráře cest,",
      "rodinné rozpočty,",
      "nákupní seznamy,",
      "porovnávání produktů,",
      "hledání nejvýhodnějších nabídek,",
      "pomoc při studiu,",
      "tvorba osobních plánů.",
      "",
      "AI dokáže během několika minut udělat práci, která by běžně zabrala hodinu hledání na internetu.",
      "",
      "---",
      "",
      "**Kolik času lze ušetřit**",
      "",
      "Skutečné úspory se liší člověk od člověka, ale i konzervativní odhad ukazuje významný přínos.",
      "",
      "Pokud AI ušetří:",
      "30 minut denně = 182 hodin ročně,",
      "1 hodinu denně = 365 hodin ročně,",
      "2 hodiny denně = 730 hodin ročně.",
      "",
      "365 hodin představuje přibližně:",
      "15 dní nepřetržitě,",
      "více než 9 pracovních týdnů,",
      "téměř dva měsíce pracovního času.",
      "",
      "Jinými slovy: AI může člověku během roku vrátit množství času odpovídající delší dovolené.",
      "",
      "---",
      "",
      "**Kolik peněz lze ušetřit**",
      "",
      "Přínos není pouze časový.",
      "AI pomáhá dělat chytřejší rozhodnutí a snižovat zbytečné výdaje.",
      "",
      "Oblasti úspor:",
      "energie,",
      "pojištění,",
      "cestování,",
      "nákupy,",
      "předplatná služeb,",
      "osobní finance.",
      "",
      "Praktické příklady:",
      "nalezení levnější letenky může ušetřit stovky až tisíce korun,",
      "optimalizace rodinného rozpočtu může odhalit zbytečné výdaje,",
      "lepší plánování nákupů omezuje impulzivní utrácení,",
      "rychlejší orientace v nabídkách vede k lepším rozhodnutím.",
      "",
      "Pokud domácnost díky lepším rozhodnutím ušetří pouze 3 až 5 % běžných výdajů, mohou roční úspory dosahovat tisíců až desetitisíců korun.",
      "",
      "---",
      "",
      "**Závěr**",
      "",
      "Největší hodnotou AI nejsou technologie samotné, ale čas a kapacita, které lidem vrací. Automatizuje rutiny, urychluje práci, pomáhá rozhodovat a zvyšuje kvalitu výsledků. Čím dříve se člověk naučí AI využívat jako každodenního pomocníka, tím více času získá pro práci, rodinu, osobní rozvoj i aktivity, které mají skutečný smysl.",
    ],
  },
  "copilot-v-poznamkach": {
    title: "Copilot v Poznámkách M365 mě fakt překvapil. A ukázal mi, kam směřuje práce s informacemi.",
    date: "2026-07-24",
    content: [
      "",
      "Copilot v Poznámkách Microsoft 365 mě fakt překvapil.",
      "A ukázal mi, jak by mohla vypadat další generace práce s informacemi.",
      "",
      "---",
      "",
      "**Wow funkce**",
      "",
      "**Celý dokument jako kontext** — nahraju soubor a Copilot nad ním dokáže diskutovat, upravovat ho, kritizovat, navrhovat změny nebo přidávat vlastní pohled přímo do poznámky.",
      "",
      "**Okamžité editace textu** — změna tónu, délky nebo stylu psaní na pár kliknutí. Jednoduchá funkce, ale obrovská úspora času.",
      "",
      "**Projekty místo izolovaných poznámek** — ke každému projektu lze přidávat dokumenty, weby, zdroje a další podklady, které vytvářejí společný kontext.",
      "",
      "**Rychlejší workflow** — místo přepínání mezi aplikacemi a ručního dohledávání informací je všechno součástí jednoho pracovního prostoru.",
      "",
      "---",
      "",
      "**Pod pokličkou: kam bych to posunul dál**",
      "",
      "**1. Hlasové poznámky s kvalitní transkripcí**",
      "Přidal bych možnost nahrávání hlasu s přesnou transkripcí a automatickým vytvářením výtahů. Pro mnoho lidí je mluvení výrazně rychlejší než psaní, takže by se z Poznámek mohl stát praktický nástroj pro zachytávání myšlenek v reálném čase.",
      "",
      "**2. Chytřejší práce s dokumenty v projektu**",
      "Chtěl bych, aby AI dokázala při odpovídání pracovat nejen s aktuálním dokumentem, ale i s ostatními materiály v projektu.",
      "",
      "Ne tak, že načte všechno najednou. To by bylo drahé, pomalé a nepřesné.",
      "",
      "Lepší přístup:",
      "každý dokument má vlastní automatické shrnutí a metadata,",
      "AI nejdřív pochopí uživatelův záměr a přeformuluje si dotaz,",
      "teprve potom vyhledá relevantní dokumenty,",
      "z nich vytáhne pouze informace potřebné pro konkrétní odpověď.",
      "",
      "Výsledkem by byly přesnější odpovědi i při práci s rozsáhlými projekty.",
      "",
      "**3. Režim \u201eHay3\u201c**",
      "Speciální mód, jehož jediným úkolem je hledat problémy.",
      "",
      "Ne potvrzovat, že je něco dobré. Naopak systematicky hledat chyby, rizika, slabá místa, logické rozpory, slepé uličky a důvody, proč by návrh mohl selhat. Ideální nástroj pro validaci nápadů před jejich realizací.",
      "",
      "**4. Projekty, které o sobě vědí**",
      "Zajímavé by bylo také velmi lehké propojení projektů mezi sebou.",
      "",
      "Každý projekt by znal jen:",
      "svůj název,",
      "účel,",
      "několik vět popisujících hlavní funkčnost.",
      "Nic víc.",
      "",
      "To by ale stačilo na to, aby AI dokázala nacházet inspiraci napříč projekty. Když by například řešila nový problém, mohla by navrhnout přístup použitý v jiném projektu, aniž by musela znát jeho kompletní obsah.",
      "",
      "---",
      "",
      "**Shrnutí**",
      "",
      "Nejvíc mě na Poznámkách Microsoft 365 nezaujaly jednotlivé AI funkce. Mnohem zajímavější je myšlenka, že se poznámky, dokumenty, zdroje a AI spojují do jednoho pracovního prostředí. Jakmile systém začne chápat souvislosti mezi dokumenty, projekty a záměrem uživatele, přestane být jen chytrým editorem textu a stane se skutečným pracovním partnerem.",
    ],
  },
  "ai-neni-nepritel": {
    title: "AI není nepřítel. Jen jsme se ještě nenaučili jeho řeč.",
    date: "2026-07-24",
    content: [
      "",
      "Víte, že:",
      "AI dnes používají stovky milionů lidí.",
      "Většina lidí říká, že jim šetří čas.",
      "A přesto ji spousta lidí nemůže vystát.",
      "",
      "To je zvláštní.",
      "Jedna technologie. Dva úplně opačný názory.",
      "A víš co?",
      "Já chápu oba.",
      "",
      "Napadlo mě, že...",
      "Možná není problém v AI.",
      "Možná je problém v tom, že jsme si zvykli, že když s náma něco komunikuje normální řečí, rozumí.",
      "Jenže AI člověk není.",
      "A vlastně je docela zvláštní, že to vůbec funguje.",
      "Žádnej jinej druh na planetě se ti nesnaží pomoct napsat e-mail, naplánovat dovolenou nebo vysvětlit hypotéku.",
      "Dobře. Procesor není druh.",
      "Právě.",
      "A přesto si s ním povídáme.",
      "Někdy překvapivě dobře.",
      "A někdy se zeptáš na jednoduchou věc a odpověď tě donutí podívat se, jestli se náhodou nevypnul internet.",
      "A přesně tam vzniká většina nedorozumění.",
      "",
      "---",
      "",
      "**Tři věci, který stojí za to pochopit**",
      "",
      "**1. AI není ani chytrá, ani hloupá**",
      "Je to nástroj.",
      "Stejně jako kladivo.",
      "Samo o sobě není ani dobrý, ani špatný.",
      "",
      "**2. Když si nerozumíme, nemáme se rádi**",
      "To platí mezi lidmi.",
      "A překvapivě i mezi lidmi a technologiemi.",
      "Čím líp pochopíš, jak se AI ptát, tím víc z ní dostaneš.",
      "",
      "**3. Budoucnost není člověk proti AI**",
      "Daleko pravděpodobnější je člověk s AI proti člověku bez AI.",
      "Ne proto, že by byl chytřejší.",
      "Protože má vedle sebe pomocníka.",
      "",
      "---",
      "",
      "**O co tu vlastně jde**",
      "",
      "Často slýcháme, že nám roboti vezmou práci.",
      "Upřímně?",
      "Tohle zní líp v titulku než v realitě.",
      "",
      "AI sama nikam nedojede.",
      "Nepřipojí kabel.",
      "Neuklidní naštvanýho zákazníka.",
      "Nepřevezme odpovědnost za rozhodnutí.",
      "",
      "Co ale umí skvěle, je zrychlit člověka.",
      "Najde informace. Pomůže s textem. Pomůže s učením. Pomůže s nápady.",
      "A najednou zvládneš za hodinu to, co ti dřív trvalo dvě.",
      "To je ten skutečnej rozdíl.",
      "",
      "---",
      "",
      "**Pod lupou**",
      "",
      "Když se podíváš do historie, pořád děláme jednu věc.",
      "Rozšiřujeme svoje schopnosti.",
      "Kolo prodloužilo naše nohy. Motor naši sílu. Internet naše znalosti.",
      "A AI?",
      "Ta rozšiřuje naše přemýšlení.",
      "",
      "Pomůže najít souvislosti.",
      "Pomůže formulovat myšlenku.",
      "Pomůže překonat prázdnou stránku.",
      "A hlavně nám uvolňuje prostor v hlavě.",
      "Míň energie na detaily. Více energie na nápady. Na tvoření. Na řešení problémů. Na lidi kolem nás.",
      "",
      "A možná právě proto je AI tak zajímavá.",
      "Není to náhrada člověka.",
      "Je to zesilovač člověka.",
      "",
      "Stejně jako jsme si kdysi ochočili psy a později kočky, dnes se učíme žít s úplně novým druhem pomocníků.",
      "Nejsou živí. Nejsou lidský. Ale pomalu se stávají součástí každodenního života.",
      "",
      "---",
      "",
      "**Shrnutí**",
      "",
      "AI není konkurence člověka.",
      "Je to jeho zesilovač.",
      "",
      "Kdo se s ní naučí mluvit, nezíská robota, kterej za něj bude žít.",
      "Získá parťáka, se kterým zvládne víc.",
      "",
      "A podle mě tímhle civilizace nekončí, zajímavej příběh spíš teprve začíná.",
    ],
  },
  "nenadavam-protoze-me-to-bavi": {
    title: "Nenadávám, protože mě to baví. Dělám to, protože to funguje.",
    date: "2026-07-19",
    content: [
      "",
      "**Proč nevybíravý jazyk u AI prokazatelně boduje — a proč to není o vulgárnosti.**",
      "",
      "---",
      "",
      'Když řeknu AI: *"Do píči, zase to nefunguje. Vyhodilo to chybu P45 na osmnáctým řádku u funkce XY. Sprav to, nebo tě vyhodím z okna."*',
      "",
      "Tak ta věta obsahuje:",
      "",
      "1. Můj emocionální stav — nejsem spokojenej, nečekej small talk",
      "2. Konkrétní problém — chyba P45, řádek 18, funkce XY",
      "3. Očekávanej výsledek — oprav to",
      "4. Urgenci — neptám se, říkám",
      "",
      "A spotřebovalo to pár desítek tokenů.",
      "",
      'Kdybych to řekl "správně": *"Dobrý den, došlo k chybě P45 na řádku 18 ve funkci XY. Mohl byste se na to prosím podívat a opravit to? Děkuji."*',
      "",
      "To je víc tokenů, míň informace, a hlavně — model neví, jak moc je to důležitý. Neví, jestli může začít rovnou, nebo jestli má čekat na další instrukce.",
      "",
      "**Čím víc slov použiju, tím větší je pravděpodobnost, že model spletu.** Každý slovo navíc je šum, kterej může model svést jinam.",
      "",
      'Když řeknu "do píči, sprav to", model ví: Mám problém. Chci ho vyřešit. Nechci diskutovat. Můžu začít rovnou.',
      "",
      'A on to udělá. Neptá se "a co přesně myslíte tím...?", neříká "určitě, rád vám pomůžu". Prostě to vezme a opraví to nejlíp, jak umí.',
      "",
      "**Paradoxně tím, že mu řeknu, ať jde do píči, o několikanásobně zefektivňuju komunikaci.**",
      "",
      "Míň tokenů. Míň kol. Míň šumu. Víc výsledků.",
      "",
      "Není to o vulgárnosti. Je to o **informační kompresi**. A to, že to funguje, není náhoda — ty modely jsou natrénovaný na miliardách textů a naučily se, že když je někdo naštvanej, nechce diskutovat. Když někdo řekne \"sprav to\", nechce slyšet \"určitě, rád vám pomůžu\".",
      "",
      "Model neví, co je \"vztek\". Ale naučil se, že když v textu vidí určitý vzorce, správná odpověď je: jednat rychle, neptat se, neotravovat.",
      "",
      "A funguje to.",
      "",
      "---",
      "",
      "*Nenadávám, protože mě to baví. Dělám to, protože to funguje.*",
      "*A to neplatí jen u počítačů.*",
    ],
  },
};

export async function generateStaticParams() {
  return Object.keys(posts).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const post = posts[slug];
  if (!post) return {};
  return {
    title: `${post.title} — Petr Piskacek`,
    description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
    openGraph: {
      title: `${post.title} — Petr Piskacek`,
      description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
      url: `https://petrpiskacek.online/blog/${slug}`,
      siteName: "Petr Piskacek",
      locale: "cs_CZ",
      type: "article",
      publishedTime: post.date,
    },
    twitter: {
      card: "summary_large_image",
      title: `${post.title} — Petr Piskacek`,
      description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
    },
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = posts[slug];

  if (!post) {
    return (
      <main className="min-h-screen bg-zinc-950 text-zinc-100">
        <div className="mx-auto max-w-2xl px-6 py-24">
          <Link href="/blog" className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors">
            ← zpět na blog
          </Link>
          <h1 className="mt-8 text-2xl font-bold">Článek nenalezen</h1>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      <article className="mx-auto max-w-2xl px-6 py-24">
        <Link href="/blog" className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors">
          ← zpět na blog
        </Link>
        <h1 className="mt-8 text-3xl font-bold tracking-tight">{post.title}</h1>
        <time dateTime={post.date} className="mt-2 block text-sm text-zinc-600">{post.date}</time>

        <div className="mt-12 space-y-4 leading-relaxed text-zinc-300">
          {post.content.map((line, i) => {
            if (line.startsWith("---")) return <hr key={i} className="border-zinc-800 my-8" />;
            if (line.startsWith("**") && line.endsWith("**")) {
              return <p key={i} className="font-semibold text-zinc-100 text-lg">{line.replace(/\*\*/g, "")}</p>;
            }
            if (line.startsWith("1. ") || line.startsWith("2. ") || line.startsWith("3. ") || line.startsWith("4. ")) {
              return <p key={i} className="text-zinc-300">{line}</p>;
            }
            if (line.startsWith("*") && line.endsWith("*") && !line.startsWith("**")) {
              return <p key={i} className="italic text-zinc-400">{line.replace(/\*/g, "")}</p>;
            }
            if (line === "") return <br key={i} />;
            return <p key={i} className="text-zinc-300">{line}</p>;
          })}
        </div>
      </article>
    </main>
  );
}
