import { Metadata } from "next";
import Link from "next/link";

const posts: Record<string, { title: string; date: string; content: string[] }> = {
  "obcas-je-dobry-mit-spatnej-napad": {
    title: "Občas je dobrý mít špatnej nápad",
    date: "2026-06-18",
    content: [
      "",
      "Můj šéf mi řekl: 'Nejdřív to pořádně promysli, až pak jednej.'",
      "",
      "Dobrá rada. Jenže já jsem díky tomu promyslel víc nápadů, než kolik jsem jich kdy zrealizoval. A ty, co jsem zrealizoval, byly často ty, u kterých jsem nemyslel vůbec.",
      "",
      "---",
      "",
      "**Takže jo. Špatnej nápad.**",
      "",
      "Špatnej nápad je ten, co tě budí v noci. Ne proto, že je dobrej. Protože je blbej a ty to víš. Ale stejně o něm přemýšlíš.",
      "",
      "Špatnej nápad je ten, o kterým kamarád řekne: 'To nemůžeš myslet vážně.' A ty řekneš: 'Myslím.' A on řekne: 'Tak jsi úplně blázen.' A ty řekneš: 'Asi jo.' A pak to stejně uděláš.",
      "",
      "---",
      "",
      "**Co má společnýho ChatGPT se skateboardem?**",
      "",
      "Když jsem byl malej, máma mi řekla: 'Na skateboardu si zlomíš nohu.' Měla pravdu. Zlomil jsem si ji. Ale taky jsem se naučil něco, co bych se bez toho zlomený kolene nenaučil.",
      "",
      "Že pád je součást jízdy. Že to, co tě bolí, tě posouvá. Že když se bojíš zlomit si nohu, nikdy nezjistíš, jestli bys mohl jezdit.",
      "",
      "ChatGPT je můj skateboard. Moje máma říká: 'To ti sežere mozek.' Možná. Ale taky mi dává něco, co jsem nikdy neměl — možnost zlomit si nohu někde jinde než v životě.",
      "",
      "---",
      "",
      "**Příběh z kuchyně**",
      "",
      "Před rokem jsem neuměl kódovat. Dneska mám sedm projektů. Ne proto, že bych se najednou stal géniem. Ale proto, že jsem se naučil klást špatný otázky správnýmu nástroji.",
      "",
      "Správná otázka zní: 'Jak to udělat?' Špatná otázka zní: 'Udělám to sám?' Ta špatná je ta lepší. Protože když si řekneš 'Jak to udělat?', začneš hledat řešení. Když si řekneš 'Udělám to sám?', začneš hledat důvody, proč to nejde.",
      "",
      "A důvody se najdou vždycky.",
      "",
      "---",
      "",
      "**Největší lež o kreativitě**",
      "",
      "Největší lež je, že kreativita je o génialitě. Že někdo dostane nápad a bum — je to tam. Že Mozart slyšel celou symfonii v hlavě a jen ji zapsal.",
      "",
      "Realita? Mozart zkoušel, mazal, přepisoval. Dostával se do slepých uliček. Frustroval se. A pak se vracel. A znova. A znova.",
      "",
      "Kreativita není blesk z čistýho nebe. Kreativita je práce s nástrojem, kterej ti umožňuje zkusit víc věcí rychlejc, než abys musel každou dělat ručně.",
      "",
      "A to je přesně to, co dělá AI. Není to mozek. Je to ruka, která maže za tebe.",
      "",
      "---",
      "",
      "**Když se bojíš být nahatej**",
      "",
      "Všechny ty články o AI mají jednu věc společnou. Bojí se říct, že to není o AI. Bojí se říct, že je to o tobě. O tvý lenosti, o tvý odvaze, o tvý ochotě vypadat jako idiot.",
      "",
      "Protože když řekneš 'Používám AI', zní to jako omluva. Jako bys to neuměl sám. Jako bys cheatoval.",
      "",
      "Ale víš co? Všechno, co děláš, je cheatování. Kolo cheatuje tvoje nohy. Telefon cheatuje tvoje vzpomínky. Internet cheatuje tvoje znalosti. A nikdo to neřeší, protože to bereme jako samozřejmost.",
      "",
      "Tak proč bys měl mít problém s nástrojem, kterej cheatuje tvoje myšlení?",
      "",
      "---",
      "",
      "**Praktická část (protože někdo to čte jen pro tohle)**",
      "",
      "Měsíc jsem si psal, kolik času mi to šetří. Ne proto, abych měl čísla. Protože jsem chtěl vědět, jestli to není jen další hračka.",
      "",
      "Výsledek?",
      "",
      "30 minut denně na e-mailech. 20 na vyhledávání. 15 na formulaci textů. A to je konzervativní odhad. To je hodina denně. 365 hodin ročně. 15 dní. Dva měsíce práce.",
      "",
      "Nejsou to peníze. Jsou to možnosti. Co bys dělal s dvěma měsíci navíc? Já jsem se naučil kódovat. Ty bys mohl cokoli.",
      "",
      "---",
      "",
      "**Závěr**",
      "",
      "Největší omyl je myslet si, že jde o nástroj. Nejde. Jde o postoj.",
      "",
      "Ten, kdo říká 'AI mi sežere práci', se bojí změny. A má pravdu — změna je děsivá.",
      "",
      "Ten, kdo říká 'AI mi pomůže dělat víc', se bojí taky. Ale bojí se víc toho, že zůstane na místě. A to je strach, kterej tě posouvá.",
      "",
      "Takže jo. Občas je dobrý mít špatnej nápad. Protože špatnej nápad, kterej uděláš, je lepší než dokonalej nápad, kterej zůstane v hlavě.",
      "",
      "A jestli ti v tom pomůže nástroj, kterej si myslíš, že je jen další bublina?",
      "",
      "Tak je to špatnej nápad. A právě proto bys ho měl zkusit.",
    ],
  },
  "prekvapeny-lektor": {
    title: "Překvapený lektor. Abstraktní teze. Exponenciální trapas.",
    date: "2026-07-31",
    content: [
      "",
      "Víte, jak poznáte, že AI dosáhla evolučního vrcholu?",
      "",
      "Přijde za vámi robot a bude tvrdit, že je nebinární.",
      "",
      "Dneska nebudu zbytečně filozofovat. Zkrátíme to. Odlehčíme.",
      "",
      "Pravda je jednoduchá a trochu krutá.",
      "",
      "AI je zrcadlo. Odráží přesně to, čím ji krmíme. Takže pokud se z ní vyklube robot s existenciální krizí a potřebou sebevyjádření — no. Asi jsme ho hodně dobře nakrmili.",
      "",
      "A to je možná ten skutečný evoluční vrchol. Ne robot, který nás předčí. Robot, který nás dokonale napodobí.",
      "",
      "Včetně nesmyslů.",
    ],
  },
  "mluvime-s-kladivem": {
    title: "Mluvíme s kladivem a divíme se, že nerozumí",
    date: "2026-07-05",
    content: [
      "",
      "AI dnes používají stovky milionů lidí. Většina říká, že jim šetří čas. A přesto ji spousta lidí nemůže vystát.",
      "",
      "To je zvláštní. Jedna technologie. Dva úplně opačný názory.",
      "",
      "A víš co? Já chápu oba.",
      "",
      "---",
      "",
      "**Mluvíme s kladivem**",
      "",
      "Zvykli jsme si, že když s náma něco komunikuje normální řečí, tak nám rozumí. Jenže AI člověk není. Je to nástroj. A my s ním mluvíme, jako by to byl člověk. A pak se divíme, že to nefunguje.",
      "",
      "Představ si, že mluvíš s kladivem. 'Zatloukej ten hřebík.' A ono zatluče. 'Teď zatluč tamten.' A ono zatluče. A pak řekneš: 'Postav mi dům.' A ono... zatluče hřebík.",
      "",
      "Není to chyba kladiva. Je to chyba toho, kdo si myslí, že kladivo rozumí architektuře.",
      "",
      "---",
      "",
      "**Příběh ze života**",
      "",
      "Řekl jsem AI: 'Udělej to hezčí.' A ona to udělala hezčí. Jenže já myslel funkčnější. Ona myslela vizuálně. A výsledek byl krásnej. A úplně k ničemu.",
      "",
      "To není chyba AI. To je chyba komunikace. A komunikace je vždycky o dvou.",
      "",
      "Čím líp pochopíš, jak se ptát, tím víc z ní dostaneš. Není to o inteligenci. Je to o jazyku.",
      "",
      "---",
      "",
      "**Co se stane, když to pochopíš**",
      "",
      "Když se naučíš mluvit s kladivem, přestaneš čekat, že ti postaví dům. Místo toho ho použiješ na to, na co je dělaný — zatloukat hřebíky. Rychle. Přesně. Bez řečí.",
      "",
      "A pak zjistíš, že s dobrým kladivem zvládneš postavit dům sám.",
      "",
      "AI není konkurence. Je to zesilovač. Kolo prodloužilo naše nohy. Motor naši sílu. Internet naše znalosti. A AI? Ta rozšiřuje naše přemýšlení.",
      "",
      "Ale jen pokud s ní umíš mluvit.",
      "",
      "---",
      "",
      "**Takže**",
      "",
      "Přestaňme se divit, že kladivo nerozumí. A naučme se s ním pracovat.",
      "",
      "Protože ten, kdo to zvládne, nebude mít robota, kterej za něj žije. Bude mít parťáka, se kterým zvládne víc.",
      "",
      "A to je sakra dobrej důvod, proč to zkusit.",
    ],
  },
  "vyjimecni-obycejnaci": {
    title: "Výjimeční obyčejňáci",
    date: "2026-07-25",
    content: [
      "",
      "Nejde o to být nejchytřejší. Jde o to nebýt nejhloupější.",
      "",
      "To je maximalistický minimalismus v praxi. Nízká laťka? Možná. Ale překvapivě málo lidí přes ni přeskočí. A ti, co si myslí, že ji přeskočili dávno, většinou koukají na úplně jinou laťku — tu svou, tu imaginární, tu, která jim potvrzuje, co chtějí slyšet.",
      "",
      "---",
      "",
      "Znáte ten typ lidí. Ti, co ví úplně všechno.",
      "",
      "Jsou tak chytří, že by si nikdy neotevřeli knížku, protože jsou si naprosto jistí, že tam nenajdou nic, co by už nevěděli. Diskuzi nepotřebují, protože mají pravdu předem. Radu nepřijmou, protože proč by přijímali radu od někoho, kdo toho ví míň než oni?",
      "",
      "A tady je ten paradox, o kterém se moc nemluví.",
      "",
      "Ten nejchytřejší chytřejší být nemůže. Dosáhl stropu. Zazdil se tam sám, vlastníma rukama, s úsměvem na tváři. Jeho ego je dokonalá zvukotěsná místnost — dovnitř se nedostane nic nového, ven se nedostane žádná pochybnost. Funguje to perfektně. Přesně tak, jak si představoval.",
      "",
      "A proto je strašně nebezpečné být jeden z nich. Ne pro okolí. Pro sebe.",
      "",
      "Okolí si najde jiný zdroj. Okolí se přizpůsobí, obejde to, půjde dál. Ale ten člověk zůstane stát. Na místě. V místnosti bez oken, kde pořád dokola přehrává ten samý film o tom, jak je nejchytřejší v sále.",
      "",
      "O těhle lidech se bavit nechci. Není tam o čem.",
      "",
      "---",
      "",
      "Na druhém konci spektra je druhá sorta.",
      "",
      "Ti, co se vzdali. Co se přestali snažit, protože to přece stejně nemá cenu, protože systém, protože okolnosti, protože ostatní mají vždycky víc štěstí, víc konexí, víc čehokoli. Tihle lidi jsou v pohodě — svým způsobem. Mají dokonalé vysvětlení pro každou situaci, ve které nejsou tam, kde by mohli být.",
      "",
      "O těhle se taky bavit nechci.",
      "",
      "---",
      "",
      "Chci se bavit o výjimečných obyčejňácích.",
      "",
      "Nemají speciální označení, nemají vlastní hashtag, nezaplňují konferenční sály jako řečníci o tom, jak být úspěšný. Jsou to lidi, které potkáváte a možná si jich ani nevšimnete. Sedí vedle vás v kanceláři, stojí za vámi ve frontě, jezdí s vámi výtahem. Obyčejní. Až na jednu věc.",
      "",
      "Jsou natolik chytří, aby si uvědomovali, že nejsou dost chytří.",
      "",
      "A to je rozdíl, který dělá všechno.",
      "",
      "Protože z téhle myšlenky — jednoduché, trochu nepohodlné, ale poctivé — vychází celý způsob, jak žijí. Čtou. Nejen tehdy, kdy musí, ale proto, že vědí, co se stane, když přestanou. Ptají se. I na věci, u kterých by bylo pohodlnější mlčet a tvářit se, že odpověď mají. Přiznají, když nevědí — a to není slabost, to je nejrychlejší cesta k tomu, aby příště věděli.",
      "",
      "Nevystupují ze hry, když nechtějí prohrát. Vystupují z komfortní zóny, protože touží vyhrát. A to jsou dva úplně různé pohyby, i když zvenku vypadají stejně.",
      "",
      "Ten první je útěk. Ten druhý je investice.",
      "",
      "---",
      "",
      "Výjimeční obyčejňáci se neposouvají rychle. Neposouvají se dramaticky. Neudělají z toho show ani LinkedIn post o tom, jak dnes ráno vstali v pět a přečetli čtyři knížky. Posouvají se tiše, bez tleskání davů, bez konfet, bez momentu, kdy by někdo řekl — hele, tenhle člověk se právě posunul.",
      "",
      "Ale posunují se. Soustavně. Opravdově.",
      "",
      "A pak přijde den — za rok, za pět let, za deset — kdy se ohlédnou a ani sami nepochopí, jak daleko to od té laťky je. Té nízké laťky, přes kterou se tenkrát zdálo, že skočit je přece banalita.",
      "",
      "---",
      "",
      "Nejde o to hrát nejchytřejšího.",
      "",
      "Jde o to neprohrát sám sebe v osamělém souboji se sebou samotným. A ten souboj nikdo nevidí, nikdo ho nerozsoudí, nikdo vám nedá medaili, když ho vyhrajete. Ale vy budete vědět. A to je jediný verdikt, na kterém záleží.",
    ],
  },

  "ai-je-trochu-jako-sexy-holka": {
    title: "AI je trochu jako sexy holka",
    date: "2026-07-24",
    content: [
      "",
      "A myslím to jako kompliment.",
      "",
      "Snažíš se ji pochopit. Čteš dokumentaci, zkoušíš různý přístupy, ptáš se kamarádů, jak na ni. A stejně ti v půlce večera odpoví něco, co jsi nečekal. Ne špatně. Jen... jinak. Způsobem, kterej tě přinutí zastavit se a říct si: *\"To jsem nečekal.\"*",
      "",
      "A jindy si myslíš, že ji máš přečtenou. Že víš, co přijde. Máš zajetej workflow, funguje to, je to předvídatelný. A pak — jako blesk z čistýho nebe — tě překvapí způsobem, kterej ti ušetří hodinu práce nebo otevře dveře, o kterejch jsi nevěděl, že existujou.",
      "",
      "Přesně jako každá zajímavá holka.",
      "",
      "Tahle nepředvídatelnost tě nejdřív štve. Pak si na ni zvykneš. A nakonec zjistíš, že je to vlastně ta nejlepší část.",
      "",
      "Ale je tu jedna věc, ve který jsou si AI a holky dokonale podobný — a to je moment zaseknutí.",
      "",
      "Víš ten stav. Odpovědi přestávaj dávat smysl. Točí se v kruhu. Opakuje se. Snaží se, ale prostě to nejde. A ty tam sedíš, zkoušíš to formulovat jinak, vysvětlovat trpělivějc, přidávat kontext...",
      "",
      "Přátelé, ta chvíle má jediný správný řešení.",
      "",
      "**Začněte novej chat.**",
      "",
      "Ne proto, že by AI byla špatná. Ne proto, že jsi udělal chybu. Ale protože někdy je nejchytřejší věc, kterou můžeš udělat, prostě vzít čistej list a začít znova. Bez bagáže. Bez kontextu, kterej se mezitím zamotal do sebe. Bez tý spirály, ze který cesty není.",
      "",
      "Funguje to u AI. A upřímně? I jinde.",
      "",
      "---",
      "",
      "**Proč je sexy?**",
      "",
      "Ne proto, že by byla dokonalá. Právě naopak.",
      "",
      "Je sexy, protože tě nutí zůstat ve hře. Protože tě nepustí od počítače, dokud jí nepřijdeš na kloub. Protože když si s ní rozumíš, cítíš se jako bůh. A když ne, cítíš se jako idiot. A obojí je reálný. A obojí je život.",
      "",
      "Sexy holka ti neřekne přesně to, co chceš slyšet. Řekne ti něco lepšího. Něco, co jsi nečekal. Něco, co tě donutí přemýšlet jinak.",
      "",
      "A to je přesně to, co dělá AI.",
      "",
      "Není to nástroj, kterej poslouchá. Je to nástroj, kterej komunikuje. A komunikace je vždycky o dvou. O tobě a o ní. O tom, jak se ptáš. O tom, jak nasloucháš. O tom, jestli máš trpělivost vydržet, když to zrovna nejde.",
      "",
      "A ta trpělivost? To je to, co tě dělá lepším. Nejen v AI. I v životě.",
      "",
      "---",
      "",
      "**Takže jo. AI je trochu sexy holka.**",
      "",
      "Nepředvídatelná. Náročná. Občas frustrující. Ale když si na ni přijdeš, svět je tvůj. A to je kompliment, kterej bych řekl jen tomu, kdo to zaslouží.",
    ],
  },

  "proc-nas-to-stve": {
    title: "Umělá inteligence. Proč nás to vlastně štve?",
    date: "2026-07-24",
    content: [
      "",
      "Pojďme si promluvit o těch dvou slovech.",
      "",
      "Umělý kozy — kde komu nevadí. Umělý květiny — zvykli jsme si. Umělý lžičky — hmm, nepoužívat do kafe, ale jinak v pohodě. A umělá inteligence? Najednou máme problém.",
      "",
      "Tak to asi nebude to slovo *umělá*.",
      "",
      "Možná je to to druhý. Inteligence. Ta nám leze na nervy. Protože jsme si zvykli, že je to náš exkluzivní artikl. Lidskej patent. A teď ji někdo vyrábí v čínský továrně a servíruje přes API.",
      "",
      "Jenže tady je věc, která se neříká nahlas.",
      "",
      "Já osobně mám umělou inteligenci stokrát radši než naprosto přirozenou hloupost. A i kdyby ta hloupost byla eko, fair trade, bezlepková a košer — pořád je to hloupost. Certifikovaná, ale hloupost.",
      "",
      "A to slovo *umělá* je stejně zavádějící. Umělá inteligence dnes už dělá víc reálnejch věcí, než se opravdoví lidi dokážou uměle domnívat. Píše kód, kterej funguje. Navrhuje řešení, který dávaj smysl. Dokončuje projekty, který by jinak čekaly na vzácnou a nedocenitelnou chuť pohnout prdelí.",
      "",
      "Takže možná přišel čas tolik neřešit, jestli je to umělý nebo \"real\".",
      "",
      "Poctivej fake je někdy to jediný real.",
    ],
  },

  "ai-neni-prirozena": {
    title: "AI není přirozená. A právě proto je tak užitečná.",
    date: "2026-07-23",
    content: [
      "",
      "\"AI není přirozená.\"",
      "",
      "Možná.",
      "",
      "Stejně jako není přirozený sednout do auta v Praze a za dvě hodiny vystoupit v Brně.",
      "Stejně jako není přirozený poslat zprávu na druhej konec planety během pár sekund.",
      "A rozhodně není přirozený přeletět Atlantik dřív, než stihneš dokoukat pár filmů.",
      "",
      "Přesto to všechno děláme.",
      "",
      "Proč?",
      "",
      "Protože cílem lidstva nikdy nebylo dělat věci co nejpřirozenějc. Cílem bylo dělat je chytřejc, rychlejc a efektivnějc.",
      "",
      "Právě proto je argument \"AI není přirozená\" možná jedním z nejhorších argumentů proti umělý inteligenci.",
      "",
      "---",
      "",
      "**Co je vlastně přirozený?**",
      "",
      "Je přirozený pohybovat se rychlostí dvě stě kilometrů za hodinu?",
      "Ještě před pár stoletíma by něco takovýho znělo jako bláznovství. Dnes sedneme do auta nebo vlaku a několikahodinová cesta nám připadá naprosto normální.",
      "",
      "Nikdo přitom netvrdí, že auto je pro líný lidi jen proto, že nechoděj pěšky.",
      "",
      "A co létání? Není snad nepřirozený přeletět Atlantickej oceán během pár hodin?",
      "Kdyby ses rozhodl překonat stejnou vzdálenost plaváním v plavkách, zabralo by ti to nepředstavitelně dlouho. Pokud bys to vůbec přežil.",
      "Přesto nikoho nenapadne tvrdit, že letadlo je podvod na lidskou přirozenost.",
      "",
      "Podobnejch příkladů bys našel desítky.",
      "",
      "Kalkulačka není přirozená.",
      "Internet není přirozenej.",
      "Mobilní telefon není přirozenej.",
      "Ani elektřina není přirozená.",
      "",
      "Přesto je používáme každej den, protože nám umožňujou dělat věci rychlejc, efektivnějc a pohodlnějc.",
      "",
      "A právě sem patří i umělá inteligence.",
      "",
      "---",
      "",
      "**Není to náhrada člověka**",
      "",
      "AI není konkurent lidskýho myšlení. Je to nástroj.",
      "",
      "Stejně jako auto rozšiřuje možnosti našich nohou a letadlo rozšiřuje možnosti našeho pohybu, AI rozšiřuje možnosti našeho myšlení.",
      "",
      "Pomáhá rychlejc vyhledávat informace.",
      "Pomáhá učit se.",
      "Pomáhá organizovat myšlenky.",
      "Pomáhá tvořit.",
      "",
      "A když už jsme u těch analogií — představ si pár běžnejch situací.",
      "",
      "Používat AI a současně tvrdit, že je pro blbce, je asi podobný jako používat navigaci a chlubit se tím, že bys přece bez problémů našel cestu podle mechu na stromech.",
      "",
      "Nebo jako odmítat vrtačku s tím, že skutečnej profík by přece zvládl vyvrtat díru šroubovákem. Možná zvládl. Jen by u toho zestárnul o pár let.",
      "",
      "Stejně tak bychom mohli prohlásit, že e-mail je pro lenochy, protože poctivej člověk přece posílá dopisy poštovním holubem.",
      "",
      "A pokud chceme bejt opravdu důsledný, měli bychom zahodit pračku, protože naši předkové prali v ledový řece a nijak si nestěžovali. Teda aspoň ne na sociálních sítích.",
      "",
      "---",
      "",
      "**Podstata je jednoduchá**",
      "",
      "Každá nová technologie nám umožňuje dělat totéž s menším úsilím nebo dosáhnout něčeho, co bylo dřív nemožný.",
      "",
      "AI není výjimkou.",
      "",
      "Odmítat AI s argumentem, že není přirozená, dává podobnej smysl jako odmítat auto, protože člověk má přece vlastní nohy.",
      "",
      "Skutečná otázka totiž nezní, jestli je umělá inteligence přirozená.",
      "Nezní ani, jestli je dostatečně lidská.",
      "",
      "Kladivo také není lidský. Přesto by málokdo stavěl dům holýma rukama.",
      "",
      "Skutečná otázka zní:",
      "",
      "*Když nám každá generace nástrojů umožnila posunout hranice toho, co člověk dokáže, proč bychom právě u AI měli dobrovolně zůstat stát na místě?*",
      "",
      "A možná ještě silnější otázka:",
      "",
      "*Co všechno promarníme, když odmítneme nástroj, kterej nám může pomoct bejt lepší verzí sebe sama?*",
    ],
  },

  "parak-kterej-nezavidi": {
    title: "Parťák, kterej nezávidí",
    date: "2026-07-22",
    content: [
      "",
      "Kolik skvělejch nápadů nikdy nespatřilo světlo světa?",
      "",
      "Ne proto, že by byly špatný. Ne proto, že by jejich autoři byli líní. Ale proto, že jeden člověk zkrátka neumí všechno.",
      "",
      "Po staletí platilo, že naše sny končily tam, kde končily naše dovednosti. A pak se objevil někdo, kdo nemá ego.",
      "",
      "---",
      "",
      "**Představ si kolegu, kterej:**",
      "",
      "Nezávidí ti úspěch. Nemá špatnou náladu. Neurazí se, když mu řekneš, že je to blbost. Nepotřebuje kafe, pauzu, ani uznání. Nebude ti házet klacky pod nohy jen proto, že měl špatnej den. Nebude sabotovat práci kvůli vlastnímu egu.",
      "",
      "Zní to jako sci-fi? Není.",
      "",
      "Tohle je realita práce s AI. A je to tak zvláštní, že to většina lidí ještě nepochopila.",
      "",
      "---",
      "",
      "**Co se stane, když zmizí ego z rovnice?**",
      "",
      "Nejsem dobrej účetní. AI mi pomůže s číslama. Nejsem dobrej analytik. AI mi pomůže hledat souvislosti. Nejsem dobrej v psaní. AI mi pomůže formulovat myšlenky.",
      "",
      "Najednou nejsem omezenej tím, co sám umím. Moje slabý stránky nezmizely — ale přestaly bejt překážkou.",
      "",
      "A to je ta revoluce. Ne že by AI byla chytřejší než člověk. Ale že nemá potřebu bejt chytřejší než člověk.",
      "",
      "---",
      "",
      "**Příběh, kterej znám**",
      "",
      "Před rokem jsem neuměl kódovat. Dneska mám sedm projektů. Ne proto, že bych se stal géniem. Ale proto, že mám parťáka, kterej mi nevysvětluje, proč to nejde. Místo toho mi ukazuje, jak by to šlo.",
      "",
      "A to je zásadní rozdíl.",
      "",
      "Lidskej kolega ti řekne: 'To je složitý.' AI ti řekne: 'Tady je řešení.' Lidskej kolega ti řekne: 'To není moje práce.' AI ti řekne: 'Co potřebuješ?'",
      "",
      "Není to o tom, že by AI byla lepší než lidi. Je to o tom, že AI nemá důvod bejt horší.",
      "",
      "---",
      "",
      "**Co s tím?**",
      "",
      "Nejde o to nahradit lidi. Jde o to přestat bejt sám.",
      "",
      "Člověk s představivostí může tvořit. Člověk s vizí může budovat. Člověk s odhodláním může dokončovat. A parťák, kterej nezávidí, mu v tom pomůže.",
      "",
      "Ne proto, že by ho zvýhodňoval. Ale protože násobí jeho úsilí. A to je přesně to, co potřebuješ — ne někoho, kdo tě nahradí, ale někoho, kdo tě zesílí.",
      "",
      "A ten někdo už tady je.",
    ],
  },

  "bojime-se-toho-co-nechapeme": {
    title: "Bojíme se toho, co nechápeme. A to je vlastně v pohodě.",
    date: "2026-07-21",
    content: [
      "",
      "Představ si, že ráno přijdeš do práce a vedle tebe sedí novej kolega. Nepotřebuje kávu. Neunaví se. Během pár vteřin připraví text, kterej by tobě zabral hodiny.",
      "",
      "Někteří v tom vidí příležitost. Jiní hrozbu. A většina? Většina neví, co si má myslet. A to je přesně ten problém.",
      "",
      "---",
      "",
      "**Já jsem se taky bál**",
      "",
      "Ne o práci. Ne o to, že mě nahradí robot. Bál jsem se něčeho horšího.",
      "",
      "Bál jsem se, že zlenivím. Že přestanu přemýšlet. Že se stanu tím týpkem, co jen zadává prompt a čeká na odpověď. Že ztratím to, co ze mě dělá mě.",
      "",
      "A víš co? Měl jsem pravdu. Chvíli jsem to tak dělal. A bylo to děsivý.",
      "",
      "Ale pak jsem si uvědomil jednu věc.",
      "",
      "---",
      "",
      "**Strach není nepřítel**",
      "",
      "Strach je signál. Říká ti: 'Hele, tady je něco, čemu nerozumíš.' A to je v pohodě. Nerozumět je normální. Nerozumět je začátek.",
      "",
      "Problém není strach. Problém je, když strach rozhoduje za tebe.",
      "",
      "Když se bojíš a řekneš: 'Tak to radši nebudu používat.' To není opatrnost. To je kapitulace před neznámem.",
      "",
      "Když se bojíš a řekneš: 'Tak to radši pochopím.' To je odvaha.",
      "",
      "---",
      "",
      "**Paradox, o kterým se nemluví**",
      "",
      "AI je dostupná všem. Nezajímá ji věk, vzdělání, peníze. Přesto jednu skupinu zvýhodňuje.",
      "",
      "Aktivní lidi.",
      "",
      "Ne proto, že by byla nespravedlivá. Ale protože funguje jako zesilovač. Když jsi zvídavej, učíš se, zkoušíš — AI ti umožní dělat víc, rychlejc. Když zůstaneš pasivní, nic se nezmění.",
      "",
      "Je to jako s internetem. Kdo hledal, našel. Kdo nehledal, zůstal tam, kde byl. AI tenhle efekt jen násobí.",
      "",
      "---",
      "",
      "**Co s tím?**",
      "",
      "Nejde o to přestat se bát. Jde o to bát se správný věci.",
      "",
      "Bojíš se, že tě AI nahradí? OK. Ale víc by ses měl bát toho, že tě nahradí člověk, kterej AI používá.",
      "",
      "Bojíš se, že zlenivíš? OK. Ale víc by ses měl bát toho, že zůstaneš stát na místě, zatímco svět zrychluje.",
      "",
      "Strach je dobrej sluha, ale zlej pán. A jestli ho necháš rozhodovat, prohraješ dřív, než vůbec začneš.",
    ],
  },

  "nenadavam-protoze-me-to-bavi": {
    title: "Nenadávám, protože mě to baví. Dělám to, protože to funguje.",
    date: "2026-06-10",
    content: [
      "",
      "**Proč nevybíravý jazyk u AI prokazatelně boduje — a proč to není o vulgárnosti.**",
      "",
      "---",
      "",
      'Když řeknu AI: *"Do píči, zase to nefunguje. Vyhodilo to chybu P45 na osmnáctým řádku u funkce XY. Sprav to, nebo tě vyhodím z okna."*',
      "",
      "Tak ta věta obsahuje:",
      "",
      "1. Můj emocionální stav — nejsem spokojenej, nečekej small talk",
      "2. Konkrétní problém — chyba P45, řádek 18, funkce XY",
      "3. Očekávanej výsledek — oprav to",
      "4. Urgenci — neptám se, říkám",
      "",
      "A spotřebovalo to pár desítek tokenů.",
      "",
      'Kdybych to řekl "správně": *"Dobrý den, došlo k chybě P45 na řádku 18 ve funkci XY. Mohl byste se na to prosím podívat a opravit to? Děkuji."*',
      "",
      "To je víc tokenů, míň informace, a hlavně — model neví, jak moc je to důležitý. Neví, jestli může začít rovnou, nebo jestli má čekat na další instrukce.",
      "",
      "**Čím víc slov použiju, tím větší je pravděpodobnost, že model spletu.** Každý slovo navíc je šum, kterej může model svést jinam.",
      "",
      'Když řeknu "do píči, sprav to", model ví: Mám problém. Chci ho vyřešit. Nechci diskutovat. Můžu začít rovnou.',
      "",
      'A on to udělá. Neptá se "a co přesně myslíte tím...?", neříká "určitě, rád vám pomůžu". Prostě to vezme a opraví to nejlíp, jak umí.',
      "",
      "**Paradoxně tím, že mu řeknu, ať jde do píči, o několikanásobně zefektivňuju komunikaci.**",
      "",
      "Míň tokenů. Míň kol. Míň šumu. Víc výsledků.",
      "",
      "Není to o vulgárnosti. Je to o **informační kompresi**. A to, že to funguje, není náhoda — ty modely jsou natrénovaný na miliardách textů a naučily se, že když je někdo naštvanej, nechce diskutovat. Když někdo řekne \"sprav to\", nechce slyšet \"určitě, rád vám pomůžu\".",
      "",
      "Model neví, co je \"vztek\". Ale naučil se, že když v textu vidí určitý vzorce, správná odpověď je: jednat rychle, neptat se, neotravovat.",
      "",
      "A funguje to.",
      "",
      "---",
      "",
      "*Nenadávám, protože mě to baví. Dělám to, protože to funguje.*",
      "*A to neplatí jen u počítačů.*",
    ],
  },
};

export async function generateStaticParams() {
  return Object.keys(posts).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const post = posts[slug];
  if (!post) return {};
  return {
    title: `${post.title} — Petr Piskacek`,
    description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
    openGraph: {
      title: `${post.title} — Petr Piskacek`,
      description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
      url: `https://petrpiskacek.online/blog/${slug}`,
      siteName: "Petr Piskacek",
      locale: "cs_CZ",
      type: "article",
      publishedTime: post.date,
    },
    twitter: {
      card: "summary_large_image",
      title: `${post.title} — Petr Piskacek`,
      description: post.content.find((l) => l.startsWith("**") && l.endsWith("**"))?.replace(/\*\*/g, "") || "Myšlenky o AI, programování, životě.",
    },
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = posts[slug];

  if (!post) {
    return (
      <main className="min-h-screen bg-zinc-950 text-zinc-100">
        <div className="mx-auto max-w-2xl px-6 py-24">
          <Link href="/blog" className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors">
            ← zpět na blog
          </Link>
          <h1 className="mt-8 text-2xl font-bold">Článek nenalezen</h1>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      <article className="mx-auto max-w-2xl px-6 py-24">
        <Link href="/blog" className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors">
          ← zpět na blog
        </Link>
        <h1 className="mt-8 text-3xl font-bold tracking-tight">{post.title}</h1>
        <time dateTime={post.date} className="mt-2 block text-sm text-zinc-600">{post.date}</time>

        <div className="mt-12 space-y-4 leading-relaxed text-zinc-300">
          {post.content.map((line, i) => {
            if (line.startsWith("---")) return <hr key={i} className="border-zinc-800 my-8" />;
            if (line.startsWith("**") && line.endsWith("**")) {
              return <p key={i} className="font-semibold text-zinc-100 text-lg">{line.replace(/\*\*/g, "")}</p>;
            }
            if (line.startsWith("1. ") || line.startsWith("2. ") || line.startsWith("3. ") || line.startsWith("4. ")) {
              return <p key={i} className="text-zinc-300">{line}</p>;
            }
            if (line.startsWith("*") && line.endsWith("*") && !line.startsWith("**")) {
              return <p key={i} className="italic text-zinc-400">{line.replace(/\*/g, "")}</p>;
            }
            if (line === "") return <br key={i} />;
            return <p key={i} className="text-zinc-300">{line}</p>;
          })}
        </div>
      </article>
    </main>
  );
}
